name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ "main" ]  # ajusta si tu branch principal no es main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
        working-directory: ./vite-jona   # 👈 instalar dependencias en la subcarpeta
      - run: npm run build
        working-directory: ./vite-jona   # 👈 hacer build en la subcarpeta
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./vite-jona/dist          # 👈 subir la carpeta dist generada
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
